new tce-make flags: -b and -v

diff --git a/tce-make b/tce-make
--- a/tce-make
+++ b/tce-make
@@ -1,12 +1,14 @@
 #!/bin/sh
 # tce-make: make tinycore extensions
+# https://github.com/yiyus/tce-make
 #
 # -- Jesus Galan (yiyus) 2015
 
-USAGE='Usage: tce-make [-h] FILES...
+USAGE='Usage: tce-make [-h] [-b|-v] FILES...
 
-Read one or more tcm files and generate .tar.gz.bfe files containing
-all the files needed to submit a tinycore extension.
+Read one or more tcm files and generate (and, by default, runs) a
+build script to generate .tar.gz.bfe files containing all the files needed
+to submit the tinycore extension indicated in the tcm file.
 
 The tcm file must contain fields as a .tcz.info file, with the following
 particularities:
@@ -30,12 +32,24 @@ EXTENSION.tcz and the corresponding EXTENSION.tar.gz.bfe file.
 
 One extension is generated for each title in the tcm file. When a new
 title is defined, the contents of all the info fields is inherited from
-the previous one, but they can be redefined.'
+the previous one, but they can be redefined.
+
+With -b, a .build script is generated, but not run. With -v, the
+output of running the script is displayed on screen.'
 
 if [ $# -lt 1 ] || [ "$1" == "-h" ]; then
 	echo "$USAGE" 1>&2
 	exit
 fi
+
+if [ "$1" = "-b" ]; then
+	shift
+	BUILDONLY=1
+elif [ "$1" = "-v" ]; then
+	shift
+	VERBOSE=1
+fi
+
 
 if [ $# -gt 1 ]; then
 	"$0" "$1" || exit 1
@@ -51,20 +65,38 @@ fi
 
 tcm="${1##*/}"
 name="${tcm%.tcm}"
+build="$name".build
 
-log="$name".log
-exec 3>&2 >"$log" 2>&1
-echo3() { echo "$@" >&3; }
-echo3 "$log"
+cat <<-'EndOfSh' > "$build"
+	#!/bin/sh
+	# Generated by tce-make
+	
+	build="${0##*/}"
+	name="${build%.build}"
+	
+	if [ "$1" != "-v" ]; then
+		log="$name".log
+		exec 3>&2 >"$log" 2>&1
+		say() { echo "$@" 1>&3; }
+		say "$log"
+	else
+		say() { echo "$@" 1>&2; }
+	fi
 
-tce-load -i "squashfs-tools" || tce-load -wi "squashfs-tools" || exit 1
+	tceload(){ tce-load -i "$1" || tce-load -wi "1" || exit 1
+	}
+	gitmaster(){ wget -q "$1"/archive/master.zip -O "$2".zip && unzip -o "$2".zip || exit 1
+	}
+	tceload squashfs-tools
+EndOfSh
 
 # $1 should be a tcm file
-/usr/bin/awk -f - "$1" <<'EndOfAwk' | sh
+/usr/bin/awk -f - "$1" >>"$build" <<'EndOfAwk'
 
 function tcm_info(tcm) {
 	if(split(tcm["Title:"], title) == 0) return
 	info = title[2]".info"
+	infos[length(infos) + 1] = info
 	if(system("rm -f "info)) exit(1)
 	for(i = 1; i <= length(fields); i++) {
 		f = fields[i]
@@ -88,12 +120,11 @@ function tcm_make(tcm) {
 	if(split(tcm["Git:"], git) == 2) {
 		zip=git[2]
 		sub(".*/", "", zip)
-		print("wget -q "git[2]"/archive/master.zip -O "zip".zip")
-		print("unzip -o "zip".zip")
+		print("gitmaster "git[2]" "zip)
 	}
 	n = split(tcm["Build-deps:"], dep)
 	for(i = 2; n >= 2 && i <= n; i++) {
-		print("( tce-load -i "dep[i]" || tce-load -wi "dep[i]" )")
+		print("tceload "dep[i])
 	}
 }
 
@@ -126,47 +157,58 @@ BEGIN{
 
 /^[ \t]/ && (field != "") { tcm[field] = tcm[field]"\n"$0 }
 
+END {
+	if(length(infos) < 1) exit(1)
+	printf("for info in ")
+	for(i in infos) printf (i > 1 ? " " : "")"\""infos[i]"\""
+	print "; do"
+}
+
 EndOfAwk
 
 if [ ! $? -eq 0 ]; then
-	echo3 "ERROR: Could not make $tcm. See $log"
+	echo "ERROR: could not generate $build from $1" 1>&2
 	exit 1
 fi
 
-for info in "$name"*.info; do
-	dir="${info%.tcz.info}"
-	tcz="$dir".tcz
+cat <<-'EndOfSh' >> "$build"
+	    dir="${info%.tcz.info}"
+	    tcz="$dir".tcz
 
-	# make tcz
-	if [ ! -d "$dir" ]; then
-		echo3 "ERROR: $dir/ not found. Cannot create $tcz"
-		exit 1
-	fi
-	rm -f "$TCZ".tcz
-	mksquashfs "$dir" "$tcz" -all-root && echo3 "$tcz"
+	    # make tcz
+	    if [ ! -d "$dir" ]; then
+	        say "ERROR: $dir/ not found. Cannot create $tcz"
+	        exit 1
+	    fi
+	    rm -f "$TCZ".tcz
+	    mksquashfs "$dir" "$tcz" -all-root && say "$tcz"
 
-	# md5, list and info
-	md5sum "$tcz" > "$tcz".md5.txt && echo3 "$tcz".md5.txt
-	(cd "$dir"; find * ! -type d) > "$tcz".list && echo3 "$tcz".list
-	sed '/^Size:/s,SIZE,'$(du "$tcz" | cut -f1)'K,
-		/Compiled for Core X.x/s/X/'$(version | cut -d. -f1)'/
-		/^Current:/s,YYYY/mm/dd,'$(date +%Y/%m/%d)',
-	' -i "$info" && echo3 "$info"
+	    # md5, list and info
+	    md5sum "$tcz" > "$tcz".md5.txt && say "$tcz".md5.txt
+	    (cd "$dir"; find * ! -type d) > "$tcz".list && say "$tcz".list
+	    sed '/^Size:/s,SIZE,'$(du "$tcz" | cut -f1)'K,
+	        /Compiled for Core X.x/s/X/'$(version | cut -d. -f1)'/
+	        /^Current:/s,YYYY/mm/dd,'$(date +%Y/%m/%d)',
+	    ' -i "$info" && say "$info"
 	
-	# pack to .tar.gz.bfe
-	tgz="$dir".tar.gz
-	bfe="$tgz".bfe
-	FILES="$tcz $tcz.info $tcz.list $tcz.md5.txt"
-	for f in $FILES; do
-		[ -f "$f" ] && continue
-		echo3 "ERROR: $f not found. Cannot create $bfe"
-		exit 1
-	done
-	dep=''
-	if [ -f "$tcz".dep ]; then
-		dep="$tcz".dep
-		echo3 "$tcz".dep
-	fi
-	tar -zcvf "$tgz" $FILES ${dep:+"$dep"} && echo3 "$tgz"
-	echo -e 'tinycore\ntinycore\n' | bcrypt "$tgz" && echo3 "$tgz".bfe
-done
+	    # pack to .tar.gz.bfe
+	    tgz="$dir".tar.gz
+	    bfe="$tgz".bfe
+	    FILES="$tcz $tcz.info $tcz.list $tcz.md5.txt"
+	    for f in $FILES; do
+	        [ -f "$f" ] && continue
+	        say "ERROR: $f not found. Cannot create $bfe"
+	        exit 1
+	    done
+	    dep=''
+	    if [ -f "$tcz".dep ]; then
+	        dep="$tcz".dep
+	        say "$tcz".dep
+	    fi
+	    tar -zcvf "$tgz" $FILES ${dep:+"$dep"} && say "$tgz"
+	    echo -e 'tinycore\ntinycore\n' | bcrypt "$tgz" && say "$tgz".bfe
+    done
+EndOfSh
+
+chmod +x "$build"
+[ -z "$BUILDONLY" ] && ./"$build" ${VERBOSE:+"-v"}
